[build]
builder = "NIXPACKS"

[deploy]
startCommand = "echo 'This is a monorepo. Deploy individual services from their directories.'"

[[services]]
name = "backend"
source = "backend/"

[services.build]
builder = "NIXPACKS"

[services.deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "frontend"
source = "web/"

[services.build]
builder = "NIXPACKS"

[services.deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"