[build]
builder = "DOCKERFILE"

[deploy]
startCommand = ""

[variables]
NODE_ENV = "production"
FRONTEND_URL = "https://summarizer.orglai.com"
BACKEND_URL = "https://backend-production-8d6f.up.railway.app"
CORS_ORIGIN = "https://summarizer.orglai.com"