[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start -- --hostname 0.0.0.0 --port $PORT"

[variables]
NODE_ENV = "production"
HOSTNAME = "0.0.0.0"
NIXPACKS_NO_CACHE = "1"